accounts/urls.py
from django.urls import path
from .views import SignUpView
from django.conf.urls.static import static

urlpatterns = [
    path("signup/", SignUpView.as_view(), name="signup"),
]

articles/urls.py
from django.urls import path

from .views import (
    ArticleCreateView,
    ArticleListView,
    ArticleDetailView,
    ArticleUpdateView,
    ArticleDeleteView,
    like_article,
    dislike_article,
)

urlpatterns = [
    path("new/", ArticleCreateView.as_view(), name="article_new"),
    path("", ArticleListView.as_view(), name="article_list"),
    path("<int:pk>/", ArticleDetailView.as_view(), name="article_detail"),
    path("<int:pk>/edit/", ArticleUpdateView.as_view(), name="article_edit"),
    path("<int:pk>/delete/", ArticleDeleteView.as_view(), name="article_delete"),
    path("like/<int:pk>", like_article, name="like_article"),
    path("dislike/<int:pk>", dislike_article, name="dislike_article"),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include("accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("articles/", include("articles.urls")),
    path("", include("pages.urls")),
]

pages/urls.py
from django.urls import path
from django.conf.urls.static import static

from .views import HomePageView, AboutPageView, ContactPageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("about/", AboutPageView.as_view(), name="about"),
    path("contact/", ContactPageView.as_view(), name="contact"),
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUser(AbstractUser):
    age = models.PositiveIntegerField(null=True, blank=True)

articles/models.py
from django.conf import settings
from django.db import models
from django.urls import reverse


class Article(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("article_detail", kwargs={"pk": self.pk})


class Like(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    is_dislike = models.BooleanField(default=False)


class Comment(models.Model):
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    comment = models.CharField(max_length=140)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True
    )

    def __str__(self):
        return self.comment

    def get_absolute_url(self):
        return reverse("article_list")

pages/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = (
            "username",
            "email",
            "age",
        )


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = CustomUser
        fields = (
            "username",
            "email",
            "age",
        )

articles/forms.py
from django import forms

from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("comment",)

accounts/views.py
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CustomUserCreationForm


class SignUpView(CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

articles/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from django.views import View
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.detail import SingleObjectMixin
from django.views.generic.edit import UpdateView, DeleteView, CreateView

from django.urls import reverse_lazy, reverse

from django.shortcuts import redirect, get_object_or_404, render

from django.http import JsonResponse

from .forms import CommentForm

from .models import Article, Like, Comment


class CommentGet(DetailView):
    model = Article
    template_name = "article_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = CommentForm()
        return context


class CommentPost(SingleObjectMixin, FormView):
    model = Article
    form_class = CommentForm
    template_name = "article_detail.html"

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)

    def form_valid(self, form):
        comment = form.save(commit=False)
        comment.article = self.object
        comment.author = self.request.user
        comment.save()
        return super().form_valid(form)

    def get_success_url(self):
        article = self.object
        return reverse("article_detail", kwargs={"pk": article.pk})


class ArticleCreateView(LoginRequiredMixin, CreateView):
    model = Article
    template_name = "article_new.html"
    fields = ("title", "body")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class ArticleListView(LoginRequiredMixin, ListView):
    model = Article
    template_name = "article_list.html"


class ArticleDetailView(LoginRequiredMixin, DetailView):
    model = Article
    template_name = "article_detail.html"
    context_object_name = "article"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        article = self.object
        comments = Comment.objects.filter(article=article)
        likes = Like.objects.filter(article=article, is_dislike=False)
        dislikes = Like.objects.filter(article=article, is_dislike=True)
        comment_form = CommentForm()
        context["comments"] = comments
        context["likes"] = likes
        context["dislikes"] = dislikes
        context["comment_form"] = comment_form
        return context

    def post(self, request, *args, **kwargs):
        view = CommentPost.as_view()
        return view(request, *args, **kwargs)


class ArticleUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Article
    fields = (
        "title",
        "body",
    )
    template_name = "article_edit.html"

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


class ArticleDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Article
    template_name = "article_delete.html"
    success_url = reverse_lazy("article_list")

    def test_func(self):
        obj = self.get_object()
        return obj.author == self.request.user


def like_article(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if Like.objects.filter(
        user=request.user, article=article, is_dislike=False
    ).exists():
        return redirect(reverse("article_detail", kwargs={"pk": pk}))
    existing_dislike = Like.objects.filter(
        user=request.user, article=article, is_dislike=True
    ).first()

    if existing_dislike:
        existing_dislike.delete()

    like = Like(user=request.user, article=article, is_dislike=False)
    like.save()

    return redirect(reverse("article_detail", kwargs={"pk": pk}))


def dislike_article(request, pk):
    article = get_object_or_404(Article, pk=pk)
    if Like.objects.filter(
        user=request.user, article=article, is_dislike=True
    ).exists():
        return redirect(reverse("article_detail", kwargs={"pk": pk}))
    existing_like = Like.objects.filter(
        user=request.user, article=article, is_dislike=False
    ).first()

    if existing_like:
        existing_like.delete()

    like = Like(user=request.user, article=article, is_dislike=True)
    like.save()

    return redirect(reverse("article_detail", kwargs={"pk": pk}))

pages/views.py
from django.views.generic import TemplateView


class HomePageView(TemplateView):
    template_name = "home.html"


class AboutPageView(TemplateView):
    template_name = "about.html"


class ContactPageView(TemplateView):
    template_name = "contact.html"

templates/about.html
{% extends "base.html" %} 

{% load static %}

{% block content %} 

    <h1>Old Dogs-New Tricks</h1>
    <h5>Who says old dogs can't learn new tricks?</h5>
<hr>
<br>
<p>
    <h2> About Old Dogs-New Tricks </h2>
</p>
<br>

<div class="flex-container-about">

    <div class="flex-about-pic">
        <img src="{% static 'img/pic4.webp' %}" width="625px" height="500px">
    </div>

    <div class="flex-about-text">
        <p>
            Old Dogs-New Tricks is a simple, straightforward blog website where people who were born and raised in an analog era can gather to learn about software development and related topics. 
        </p>
        <p>
            At this time only registered users are able to create new post, ask questions, provide answers, leave comments, and up or down vote existing posts. But signing up is quick, free and easy! 
        </p>
        <p>
            Want to validate your opinion? Verify a hunch? Or just ask a simple question to find out how others might approach issues pertaining to software devlopement, building websites, user interfaces, and user experiences.
        </p>
        <p>
            The key is to keep things simple; blog post, comments, questions, and answers should avoid using technical language and industry jargon. Remember, this blog is for people who didn't grow up in a digital age!
        </p>
        <p>
            As always, inciting violence, using profanity, threatening or disrespecting others is strictly prohibited and will result in the immediate removal and permanent banning of your account. 
        </p>
        <p>
            So have fun, offer advice, ask questions and lets see if we can actually teach old dogs a few new tricks.
        </p>
    </div>

</div>
<br>
<br>
{% endblock %}

templates/article_delete.html
{% extends "base.html" %}

{% block content %}
    <h1>Old Dogs-New Tricks</h1>
    <h5>Who says old dogs can't learn new tricks?</h5>
<hr>
<br>
    <h3>Are you sure you want to delete this Post?</h3>
<br>
<br>
    <h4>{{ object.title }}</h4>

    <p>by {{ object.author }} | {{ object.date }}</p>
    <p>{{ object.body }}</p>
    
    <form action="" method="post">
        {% csrf_token %}
        <p>
            <h3>Delete "{{ article.title }}" <button class="btn btn-danger ml-2" type="submit">Confirm</button></h3>
        </p>
    </form>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
{% endblock content %}

templates/article_detail.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %} Post Details {% endblock title %}

{% block content %}
    <h1>Old Dogs-New Tricks</h1>
<h5>Who says old dogs can't learn new tricks?</h5>
<hr>
  <div class="article-entry">
    <h2>{{ article.title }}</h2>
    <p>by {{ article.author }} | {{ article.date }}</p>
    <p>{{ article.body }}</p>
  </div>
  <p>
    {% if article.author.pk == request.user.pk %}
      <a href="{% url 'article_edit' article.pk %}" class="btn btn-primary ml-2">Edit</a> &nbsp &nbsp &nbsp &nbsp
      <a href="{% url 'article_delete' article.pk %}" class="btn btn-danger ml-2">Delete</a>
      {% else %}
      <hr>
      <div class="d-flex justify-content-evenly">
        <form method="POST" action="{% url 'like_article' article.pk %}">
          {% csrf_token %}
          <div class="flex-like">
              <button type="submit" class="btn-up"><i class="fa-regular fa-thumbs-up" >
              </i> Like </button> &nbsp<b> {{ likes.count }} </b>
          </div>
        </form>
        <form method="POST" action="{% url 'dislike_article' article.pk %}">
          {% csrf_token %}
          <div class="flex-like">
              <button type="submit" class="btn-down"><i class="fa-regular fa-thumbs-down" >
              </i> Dislike </button> &nbsp <b> {{ dislikes.count }} </b>
          </div>
        </form>
      </div>
    {% endif %}
  </p>
<hr>
  <h4>Previous Comments</h4>
{% for comment in article.comment_set.all %}
  <p>by {{ comment.author }} &#8226; {{ comment }}</p>
{% endfor %}
<hr>
  <h4>Add a New Comment</h4>
    <form action method="post">
      {% csrf_token %}
      <div id="div_id_comment" class="mb-3">
        <label for="id_comment" class="form-labe requiredField"></label>
        <input type="text" name="comment" maxlength="140" class="textinput form-control" 
        required id="id_comment" placeholder="Write your comment here">
<br>
      </div class="comment-field">
        <button class="btn btn-success ml-2" type="submit">Save</button> &nbsp &nbsp &nbsp &nbsp
        <a href="{% url 'article_list' %}" class="btn btn-outline-success ml-2">View All Posts</a>
      </div>
    </form>
<br>
<br>
{% endblock content %}

templates/article_edit.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block content %}
  <h1>Old Dogs-New Tricks</h1>
  <h5>Who says old dogs can't learn new tricks?</h5>
<hr>
  <h2>Edit This Post</h2>
  <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
    <button class="btn btn-info ml-2" type="submit">Update</button>
  </form>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
{% endblock content %}

templates/article_list.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}Post Listings{% endblock title %}

{% block content %}
    <h1>Old Dogs-New Tricks</h1>
<h5>Who says old dogs can't learn new tricks?</h5>
<hr>
<br>
<br>
{% for article in article_list %}
  <div class="card">
    <div class="card-header">
      <span class="fw-bold fst-italic">
        <a href="{{ article.get_absolute_url }}">{{ article.title }}</a>
      </span> &#8226;
      <span class="text-muted">by {{ article.author }} |
        {{ article.date }}</span>
    </div>
    <div class="card-body">
      {{ article.body|truncatewords:70 }}
      <div class="d-flex justify-content-evenly">
        {% if article.author.pk == request.user.pk %}
          <a href="{% url 'article_edit' article.pk %}"><b>Edit</b></a>
          <a href="{% url 'article_delete' article.pk %}"><b>Delete</b></a>
        {% endif %}
          <!-- <a href="{{ article.get_absolute_url }}"><b>Add Comment</b></a> -->
      </div>
    </div>
    <div class="card-footer">
      <div class="d-flex justify-content-evenly">
        <u><b>Previous Comments:</b></u>
      </div>
      {% for comment in article.comment_set.all %}
      <p>
        <span class="fw-bold fst-italic">
          {{ comment.author }} &#8226;
        </span>
        {{ comment }}
      </p>
      {% endfor %}
    </div>
  </div>
<br>
<br>
{% endfor %}
{% endblock content %}

templates/article_new.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %} Add a Post {% endblock title %}

{% block content %}
  <h1>Old Dogs-New Tricks</h1>
    <h5>Who says old dogs can't learn new tricks?</h5>
<hr>
<br>
  <h2>Add Your Post</h2>
  <form action="" method="post">
      {% csrf_token %}
      {{ form|crispy }}
    <button class="btn btn-success ml-2" type="submit">Save</button>
  </form>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block title %}Old Dogs-New Tricks{% endblock title %}</title>

  <script src="https://kit.fontawesome.com/9d6d2df8c5.js" crossorigin="anonymous"></script>
  
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" 
    integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" 
    crossorigin="anonymous"/>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" 
    integrity="sha512-1ycn6IcaQQ40/MKBW2W4Rhis/DbILU74C1vSrLJxCq57o941Ym01SwNsOMqvEBFlcgUa6xLiPY/NS5R+E6ztJQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer" />
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}"/>

  {% block styles %}{% endblock %} 
</head>

<body>
  <nav class="navbar bg-body-tertiary">
    <div class="container-fluid">
        <a class="nav-link" href="{% url 'home' %}">Home</a>
        <a class="nav-link" href="{% url 'about' %}">About</a>
        <a class="nav-link" href="{% url 'contact' %}">Contact</a>
      {% if user.is_authenticated %}
        <a class="nav-link" href="{% url 'article_list' %}">View All Posts</a>
        <a class="nav-link" href="{% url 'article_new' %}">Add a Post</a>
        <a class="nav-link" href="{% url 'logout' %}">Log Out</a>
      {% else %} 
        <a class="nav-link" href="{% url 'login' %}">Log In</a>
        <a class="nav-link" href="{% url 'signup' %}">Sign Up</a>
      {% endif %}
    </div>
  </nav>
<main>
  <div class="container">{% block content %}{% endblock content %}</div>
</main>
  <footer>
    <div class="container-footer">
        <div class="icons">
        <a href=""><em class="fab fa-twitter fa-2x"></em></a>
        <a href=""><em class="fab fa-instagram fa-2x"></em></a>
        <a href=""><em class="fab fa-facebook fa-2x"></em></a>
        <a href=""><em class="fab fa-whatsapp fa-2x"></em></a>
        </div>
        <div class="copy">
        <a>Copyright &copy; 2023</a>
        </div>
        <div class="logo">
        <a>Dog Byte Ventures LLC</a>
        </div>
    </div>
  </footer>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-ENjdO4Dr2bkBIFxQpeoTz1HIcje39Wm4jDKdf19U8gI4ddQ3GYNS7NTKfAdVQSZe" 
    crossorigin="anonymous">
  </script>
  {% block scripts %}{% endblock %}
</body>
</html>

templates/contact.html
{% extends "base.html" %} 
{% load crispy_forms_tags %}

{% load static %}

{% block content %} 

        <h1>Old Dogs-New Tricks</h1>
<h5>Who says old dogs can't learn new tricks?</h5>
<hr>
<br>
    <p>
        <h2> Contact Us </h2>
    </p>
<br>
    <div class="flex-container-contact">
    <br>
        <div class="flex-contact-text">
        <p>
            Phone: (222) 333-4444
        </p>
    <br>
    <br>
        <p>
            Email: olddogs-newtricks@email.com
        </p>
    <br>
    <br>
        <p>
            Address: 
        </p>
        <p>
            &nbsp &nbsp Dog Byte Ventures
        </p>
        <p>
            &nbsp &nbsp 1234 This Street
        </p>
        <p>
            &nbsp &nbsp Anytown, AK  98765
        </p>
    <br>
    <br>
    <br>
        <p>
            https://www.olddogs-newtricks.com
        </p>
        </div>

        <div class="flex-contact-pic">
            <img src="{% static 'img/pic5.jpg' %}" width="625px" height="500px">
        </div>
    </div>
<br>
<br>
{% endblock %}

templates/home.html
{% extends "base.html" %}
{% load static %}

{% block title %} Old Dogs-New Tricks {% endblock title %}

{% block content %}


{% if user.is_authenticated %}
    <h1>Old Dogs-New Tricks</h1>
    <h5>Who says old dogs can't learn new tricks?</h5>
<hr>
<br>
    <h3>Hi {{ user.username }}...Good to have you back again!</h3>
    <br>
    <div class="flex-container-login-pic">
        <div>
            <img width="750" src="{% static 'img/pic6.jpg' %}" class="wdn-stretch rounded-corners"> 
        </div>
    </div>
<br>
<br>
{% else %}
    <h1>Old Dogs-New Tricks</h1>
    <h5>Who says old dogs can't learn new tricks?</h5>
<hr>
<br>
<br>
    <div class="flex-container-home-pic">
        <div>
            <img  width="800" src="{% static 'img/pic9.webp' %}" class="wdn-stretch rounded-corners"> 
        </div>
    </div>
<br>
<br>
{% endif %}
{% endblock content %}